### ISSUE TITLE
gpower listで出そうとしている文字列が長すぎてエラー

### ISSUE THREAD

**Issue by unasuke** [unasuke/bot-bahamut#57]
#52 の影響？

```
2022-05-31T10:48:53.985618+00:00 app[bot.1]: [ERROR : et-40 @ 2022-05-31 10:48:53.985] Exception: #<Discordrb::Errors::MessageTooLong: Message over the character limit (2049 > 2000)>
2022-05-31T10:48:53.985641+00:00 app[bot.1]: [ERROR : et-40 @ 2022-05-31 10:48:53.985] /app/vendor/bundle/ruby/2.7.0/gems/discordrb-3.3.0/lib/discordrb/api/channel.rb:87:in `rescue in create_message'
2022-05-31T10:48:53.985653+00:00 app[bot.1]: [ERROR : et-40 @ 2022-05-31 10:48:53.985] /app/vendor/bundle/ruby/2.7.0/gems/discordrb-3.3.0/lib/discordrb/api/channel.rb:75:in `create_message'
2022-05-31T10:48:53.985665+00:00 app[bot.1]: [ERROR : et-40 @ 2022-05-31 10:48:53.985] /app/vendor/bundle/ruby/2.7.0/gems/discordrb-3.3.0/lib/discordrb/bot.rb:367:in `send_message'
2022-05-31T10:48:53.985677+00:00 app[bot.1]: [ERROR : et-40 @ 2022-05-31 10:48:53.985] /app/vendor/bundle/ruby/2.7.0/gems/ruboty-discord-1.0.0/lib/ruboty/adapters/discord.rb:22:in `say'
2022-05-31T10:48:53.985695+00:00 app[bot.1]: [ERROR : et-40 @ 2022-05-31 10:48:53.985] /app/vendor/bundle/ruby/2.7.0/gems/ruboty-1.3.1/lib/ruboty/robot.rb:39:in `say'
2022-05-31T10:48:53.985709+00:00 app[bot.1]: [ERROR : et-40 @ 2022-05-31 10:48:53.985] /app/vendor/bundle/ruby/2.7.0/gems/ruboty-1.3.1/lib/ruboty/message.rb:44:in `reply'
2022-05-31T10:48:53.985721+00:00 app[bot.1]: [ERROR : et-40 @ 2022-05-31 10:48:53.985] /app/actions/ikasuke.rb:96:in `gearpower_list'
2022-05-31T10:48:53.985745+00:00 app[bot.1]: [ERROR : et-40 @ 2022-05-31 10:48:53.985] /app/handlers/ikasuke.rb:25:in `gpower'
2022-05-31T10:48:53.985761+00:00 app[bot.1]: [ERROR : et-40 @ 2022-05-31 10:48:53.985] /app/vendor/bundle/ruby/2.7.0/gems/ruboty-1.3.1/lib/ruboty/action.rb:16:in `call'
2022-05-31T10:48:53.985778+00:00 app[bot.1]: [ERROR : et-40 @ 2022-05-31 10:48:53.985] /app/vendor/bundle/ruby/2.7.0/gems/ruboty-1.3.1/lib/ruboty/handlers/base.rb:32:in `block in call'
2022-05-31T10:48:53.985789+00:00 app[bot.1]: [ERROR : et-40 @ 2022-05-31 10:48:53.985] /app/vendor/bundle/ruby/2.7.0/gems/ruboty-1.3.1/lib/ruboty/handlers/base.rb:31:in `each'
2022-05-31T10:48:53.985801+00:00 app[bot.1]: [ERROR : et-40 @ 2022-05-31 10:48:53.985] /app/vendor/bundle/ruby/2.7.0/gems/ruboty-1.3.1/lib/ruboty/handlers/base.rb:31:in `inject'
2022-05-31T10:48:53.985812+00:00 app[bot.1]: [ERROR : et-40 @ 2022-05-31 10:48:53.985] /app/vendor/bundle/ruby/2.7.0/gems/ruboty-1.3.1/lib/ruboty/handlers/base.rb:31:in `call'
2022-05-31T10:48:53.985824+00:00 app[bot.1]: [ERROR : et-40 @ 2022-05-31 10:48:53.985] /app/vendor/bundle/ruby/2.7.0/gems/ruboty-1.3.1/lib/ruboty/robot.rb:29:in `block in receive'
2022-05-31T10:48:53.985834+00:00 app[bot.1]: [ERROR : et-40 @ 2022-05-31 10:48:53.985] /app/vendor/bundle/ruby/2.7.0/gems/ruboty-1.3.1/lib/ruboty/robot.rb:29:in `each'
```

**Comment by nikuzuki** [comment]
> Message over the character limit (2049 > 2000)

なるほどね
